name: Testing & Deploying the application

on:
    push:
        branches:
            - main

jobs:
    proof-of-concept-one_build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Create build folder
                run: mkdir ./build
            -   name: Build the application
                run: |
                    docker build -t proof-of-concept-one_builder ./proof-of-concept-one
                    docker run -d --name proof-of-concept-one_builder -p 8080:80 proof-of-concept-one_builder
                    mkdir ./output
                    docker cp proof-of-concept-one_builder:/usr/local/apache2/htdocs/ ./output
                    docker stop proof-of-concept-one_builder
                    docker rm proof-of-concept-one_builder
                    cp -r ./output/htdocs/. ./build/
            -   name: Upload build artifact
                uses: actions/upload-artifact@v4
                with:
                    name: proof-of-concept-one_build
                    path: ./build
    proof-of-concept-two_build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Create build folder
                run: mkdir ./build
            -   name: Build the application
                run: |
                    docker build -t proof-of-concept-two_builder ./proof-of-concept-one
                    docker run -d --name proof-of-concept-two_builder -p 8080:80 proof-of-concept-two_builder
                    mkdir ./output
                    docker cp proof-of-concept-two_builder:/usr/local/apache2/htdocs/ ./output
                    docker stop proof-of-concept-two_builder
                    docker rm proof-of-concept-two_builder
                    cp -r ./output/htdocs/. ./build/
            -   name: Upload build artifact
                uses: actions/upload-artifact@v4
                with:
                    name: proof-of-concept-two_build
                    path: ./build
    prototype_build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Create build folder
                run: mkdir ./build
            -   name: Build the application
                run: |
                    docker build -t prototype_builder ./proof-of-concept-one
                    docker run -d --name prototype_builder -p 8080:80 prototype_builder
                    mkdir ./output
                    docker cp prototype_builder:/usr/local/apache2/htdocs/ ./output
                    docker stop prototype_builder
                    docker rm prototype_builder
                    cp -r ./output/htdocs/. ./build/
            -   name: Upload build artifact
                uses: actions/upload-artifact@v4
                with:
                    name: prototype_build
                    path: ./build
    app_build:
        needs: [proof-of-concept-one_build, proof-of-concept-two_build, prototype_build]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Create build folder
                run: mkdir ./build
            -   name: Download proof-of-concept-one_build into build folder
                uses: actions/download-artifact@v4
                with:
                    name: proof-of-concept-one_build
                    path: ./build/proof-concept-one
            -   name: Download proof-of-concept-two_build into build folder
                uses: actions/download-artifact@v4
                with:
                    name: proof-of-concept-two_build
                    path: ./build/proof-concept-two
            -   name: Download prototype_build into build folder
                uses: actions/download-artifact@v4
                with:
                    name: prototype_build
                    path: ./build/prototype
            -   name: Upload build artifact
                uses: actions/upload-artifact@v4
                with:
                    name: app_build
                    path: ./build
    app_deploy:
        needs: [app_build]
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        permissions:
            contents: "read"
            id-token: "write"
            pages: "write"
            actions: "write"
            checks: "write"
            deployments: "write"
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Download build artifact
                uses: actions/download-artifact@v4
                with:
                    name: app_build
                    path: ./build
            -   name: Setup pages
                uses: actions/configure-pages@v5
            -   name: Upload artifacts
                uses: actions/upload-pages-artifact@v3
                with:
                    path: "./build"
            -   name: Deploy to GitHub-Pages
                uses: actions/deploy-pages@v4
                id: deployment
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
