name: Testing & Deploying the application

on:
    push:
        branches:
            - main

jobs:
    proof-of-concept-one_check-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 20.x
            - name: Run check-tests
              run: |
                    cd ./proof-of-concept-one
                    npm install
                    npm run test:check
    proof-of-concept-one_unit-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 20.x
            - name: Run unit-tests
              run: |
                    cd ./proof-of-concept-one
                    npm install
                    npm run test:unit
    proof-of-concept-one_build-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Setup NodeJS
                uses: actions/setup-node@v4
                with:
                    node-version: 20.x
            -   name: Build the application
                run: |
                    cd ./proof-of-concept-one
                    npm install
                    npm run build
    proof-of-concept-one_docker-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v5
            -   name: Run docker container
                run: |
                    cd ./proof-of-concept-one
                    docker build -t app ./
                    docker run -d -p 80:80 --name container app
                    docker stop container
                    docker rm container
    proof-of-concept-two_check-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 20.x
            - name: Run check-tests
              run: |
                    cd ./proof-of-concept-two
                    npm install
                    npm run test:check
    proof-of-concept-two_unit-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 20.x
            - name: Run unit-tests
              run: |
                    cd ./proof-of-concept-two
                    npm install
                    npm run test:unit
    proof-of-concept-two_build-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Setup NodeJS
                uses: actions/setup-node@v4
                with:
                    node-version: 20.x
            -   name: Build the application
                run: |
                    cd ./proof-of-concept-two
                    npm install
                    npm run build
    proof-of-concept-two_docker-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v5
            -   name: Run docker container
                run: |
                    cd ./proof-of-concept-two
                    docker build -t app ./
                    docker run -d -p 80:80 --name container app
                    docker stop container
                    docker rm container
    prototype_check-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 20.x
            - name: Run check-tests
              run: |
                    cd ./prototype
                    npm install
                    npm run test:check
    prototype_unit-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 20.x
            - name: Run unit-tests
              run: |
                    cd ./prototype
                    npm install
                    npm run test:unit
    prototype_build-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Setup NodeJS
                uses: actions/setup-node@v4
                with:
                    node-version: 20.x
            -   name: Build the application
                run: |
                    cd ./prototype
                    npm install
                    npm run build
    prototype_docker-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v5
            -   name: Run docker container
                run: |
                    cd ./prototype
                    docker build -t app ./
                    docker run -d -p 80:80 --name container app
                    docker stop container
                    docker rm container
    proof-of-concept-one_deploy:
        needs: [proof-of-concept-one_check-test, proof-of-concept-one_unit-test, proof-of-concept-one_build-test, proof-of-concept-one_docker-test]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: _?_
                uses: Dylan700/sftp-upload-action@latest
                with:
                    server: ${{ secrets.SFTP_HOST }}
                    username: ${{ secrets.SFTP_USER }}
                    password: ${{ secrets.SFTP_PASSWORD }}
                    port: 22
                    uploads: |
                        ./proof-of-concept-one => /root/projects/automatic/proof-of-concept-one
    proof-of-concept-two_deploy:
        needs: [proof-of-concept-two_check-test, proof-of-concept-two_unit-test, proof-of-concept-two_build-test, proof-of-concept-two_docker-test]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: _?_
                uses: Dylan700/sftp-upload-action@latest
                with:
                    server: ${{ secrets.SFTP_HOST }}
                    username: ${{ secrets.SFTP_USER }}
                    password: ${{ secrets.SFTP_PASSWORD }}
                    port: 22
                    uploads: |
                        ./proof-of-concept-two => /root/projects/automatic/proof-of-concept-two
    prototype_deploy:
        needs: [prototype_check-test, prototype_unit-test, prototype_build-test, prototype_docker-test]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: _?_
                uses: Dylan700/sftp-upload-action@latest
                with:
                    server: ${{ secrets.SFTP_HOST }}
                    username: ${{ secrets.SFTP_USER }}
                    password: ${{ secrets.SFTP_PASSWORD }}
                    port: 22
                    uploads: |
                        ./prototype => /root/projects/automatic/prototype
    app_deploy:
        needs: [proof-of-concept-one_deploy, proof-of-concept-two_deploy, prototype_deploy]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: _?_
                uses: appleboy/ssh-action@latest
                with:
                    host: ${{ secrets.SFTP_HOST }}
                    username: ${{ secrets.SFTP_USER }}
                    key: ${{ secrets.SFTP_PASSWORD }}
                    script: |
                        docker compose --project-directory /root/projects/automatic/proof-of-concept-one -f ./compose.yaml build project-thesis_proof-of-concept-one --no-cache
                        docker compose --project-directory /root/projects/automatic/proof-of-concept-two -f ./compose.yaml build project-thesis_proof-of-concept-two --no-cache
                        docker compose --project-directory /root/projects/automatic/prototype -f ./compose.yaml build project-thesis_prototype --no-cache
                        docker compose --project-directory /root/projects/automatic/proof-of-concept-one -f ./compose.yaml down project-thesis_proof-of-concept-one
                        docker compose --project-directory /root/projects/automatic/proof-of-concept-two -f ./compose.yaml down project-thesis_proof-of-concept-two
                        docker compose --project-directory /root/projects/automatic/prototype -f ./compose.yaml down project-thesis_prototype
                        docker compose --project-directory /root/projects/automatic/proof-of-concept-one -f ./compose.yaml up project-thesis_proof-of-concept-one -d --build
                        docker compose --project-directory /root/projects/automatic/proof-of-concept-two -f ./compose.yaml up project-thesis_proof-of-concept-two -d --build
                        docker compose --project-directory /root/projects/automatic/prototype -f ./compose.yaml up project-thesis_prototype -d --build
