name: Testing & Deploying the application

on:
    push:
        branches:
            - main

jobs:
    proof_of_concept_one-build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout the code
                uses: actions/checkout@v5
            -   name: Setup NodeJS
                uses: actions/setup-node@v4
                with:
                    node-version: 20.x
            -   name: Build the application
                run: |
                    cd ./proof-of-concept-one
                    npm install
                    npm run build
            -   name: Upload build artifact
                uses: actions/upload-artifact@v4
                with:
                    name: proof_of_concept_one-build
                    path: ./proof-of-concept-one/build
    proof_of_concept_two-build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout the code
                uses: actions/checkout@v5
            -   name: Setup NodeJS
                uses: actions/setup-node@v4
                with:
                    node-version: 20.x
            -   name: Build the application
                run: |
                    cd ./proof-of-concept-two
                    npm install
                    npm run build
            -   name: Upload build artifact
                uses: actions/upload-artifact@v4
                with:
                    name: proof_of_concept_two-build
                    path: ./proof-of-concept-two/build
    prototype-build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout the code
                uses: actions/checkout@v5
            -   name: Setup NodeJS
                uses: actions/setup-node@v4
                with:
                    node-version: 20.x
            -   name: Build the application
                run: |
                    cd ./prototype
                    npm install
                    npm run build
            -   name: Upload build artifact
                uses: actions/upload-artifact@v4
                with:
                    name: prototype-build
                    path: ./prototype/build
    app-deployment:
        needs: [prototype-build]
        environment:
            name: github-pages
            url: ${ steps.deployment.outputs.page_url }}
        permissions:
            contents: read
            id-token: write
            pages: write
            actions: write
            checks: write
            deployments: write
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout the code
                uses: actions/checkout@v5
            -   name: Download build artifact
                uses: actions/download-artifact@v4
                with:
                    name: prototype-build
                    path: ./build
            -   name: Setup pages
                uses: actions/configure-pages@v5
            -   name: Upload artifacts
                uses: actions/upload-pages-artifact@v3
                with:
                    path: ./build
            -   name: Deploy to GitHub-Pages
                uses: actions/deploy-pages@v4
                id: deployment
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
