import MatchingGame from "$components/Games/MatchingGame/MatchingGame.svelte";

export const quiz: MatchingGame = new MatchingGame(
    [
        [
            { answer: "Schmied",        correct: true  },
            { answer: "Fleischer",      correct: false },
            { answer: "Bäcker",         correct: false },
            { answer: "Bader",          correct: false },
            { answer: "Tuchmacher",     correct: false },
            { answer: "Gerber",         correct: false },
            { answer: "Schuhmacher",    correct: false },
            { answer: "Krämer",         correct: false },
            { answer: "Fettkrämer",     correct: false },
            { answer: "Abdecker",       correct: false },
        ],
        [
            { answer: "Schmied",        correct: false },
            { answer: "Fleischer",      correct: false },
            { answer: "Bäcker",         correct: true  },
            { answer: "Bader",          correct: false },
            { answer: "Tuchmacher",     correct: false },
            { answer: "Gerber",         correct: false },
            { answer: "Schuhmacher",    correct: false },
            { answer: "Krämer",         correct: false },
            { answer: "Fettkrämer",     correct: false },
            { answer: "Abdecker",       correct: false },
        ],
        [
            { answer: "Schmied",        correct: false },
            { answer: "Fleischer",      correct: true },
            { answer: "Bäcker",         correct: false },
            { answer: "Bader",          correct: false },
            { answer: "Tuchmacher",     correct: false },
            { answer: "Gerber",         correct: false },
            { answer: "Schuhmacher",    correct: false },
            { answer: "Krämer",         correct: false },
            { answer: "Fettkrämer",     correct: false },
            { answer: "Abdecker",       correct: false },
        ],
        [
            { answer: "Schmied",        correct: false },
            { answer: "Fleischer",      correct: false },
            { answer: "Bäcker",         correct: false },
            { answer: "Bader",          correct: false },
            { answer: "Tuchmacher",     correct: false },
            { answer: "Gerber",         correct: true  },
            { answer: "Schuhmacher",    correct: false },
            { answer: "Krämer",         correct: false },
            { answer: "Fettkrämer",     correct: false },
            { answer: "Abdecker",       correct: false },
        ],
        [
            { answer: "Schmied",        correct: false },
            { answer: "Fleischer",      correct: false },
            { answer: "Bäcker",         correct: false },
            { answer: "Bader",          correct: false },
            { answer: "Tuchmacher",     correct: false },
            { answer: "Gerber",         correct: false },
            { answer: "Schuhmacher",    correct: true  },
            { answer: "Krämer",         correct: false },
            { answer: "Fettkrämer",     correct: false },
            { answer: "Abdecker",       correct: false },
        ],
        [
            { answer: "Schmied",        correct: false },
            { answer: "Fleischer",      correct: false },
            { answer: "Bäcker",         correct: false },
            { answer: "Bader",          correct: false },
            { answer: "Tuchmacher",     correct: false },
            { answer: "Gerber",         correct: false },
            { answer: "Schuhmacher",    correct: false },
            { answer: "Krämer",         correct: true  },
            { answer: "Fettkrämer",     correct: false },
            { answer: "Abdecker",       correct: false },
        ],
        [
            { answer: "Schmied",        correct: false },
            { answer: "Fleischer",      correct: false },
            { answer: "Bäcker",         correct: false },
            { answer: "Bader",          correct: false },
            { answer: "Tuchmacher",     correct: false },
            { answer: "Gerber",         correct: false },
            { answer: "Schuhmacher",    correct: false },
            { answer: "Krämer",         correct: false },
            { answer: "Fettkrämer",     correct: true  },
            { answer: "Abdecker",       correct: false },
        ],
    ],
);

export const handwerk: string[] = [
    "Metallverarbeitung",
    "Getreideverarbeitung",
    "Fleischverarbeitung",
    "Lederverarbeitung",
    "Feinlederverarbeitung",
    "Gemischtwarenhandel",
    "Handel mit Butter, Öl, Speck etc."
];